#+title: Org Contacts Extended
#+date: <2022-08-15 Mon>
#+author: Thomas Freeman
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.1 (Org mode 9.5.4)

#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t num:nil

*This package is currently a work in progress and is not ready for daily use.*

Expanding on the power of org-contacts.el. This is a fork of ~org-contacts.el~.

* Purpose

Org Contacts Extended is designed with the following principles in mind:

1. As opposed to storing multiple user addresses and info under a single property, use multiple named properties to store contact information. For example, instead of having multiple email addresses listed under a contact under a single ~:EMAIL:~, store each address under properties such as ~:WORK_EMAI:L~, ~:HOME_EMAIL:~, and ~:OTHER_EMAIL:~, etc. This makes searching for the correct information easier and works well with the Emacs completion system for interactively choosing contact information.
2. Allow the user to expand on the different properties for contact information so there is no limit to how much information can be stored. A user can define more contact information types under general categories using the Emacs ~M-x customize~ interface. For example, the "Address" category could be expanded to contain different types of address properties such as "WORK_ADDRESS", "HOME_ADDRESS", "VACATION_HOME_ADDRESS", and so on. Each property would refer to a single address.
3. Create functions to use contact information outside of Emacs, such as using email software outside of Emacs to compose a message.
